#ifndef OX_WRAPPER_VERSION_H
#define OX_WRAPPER_VERSION_H

#define OX_WRAPPER_VERSION_MAJOR 0
#define OX_WRAPPER_VERSION_MINOR 1
#define OX_WRAPPER_VERSION_SUFFIX "alpha"
#define OX_WRAPPER_VERSION_CODENAME "PERUN"


#define OX_WRAPPER_USE_CPU_INTRINSICS

#endif
