circle = OxProgram.new("circle.ptx", OxProgramSource.file, "__ox_intersect__")
black_body = OxBlackBody.new(OxRayPayloadType["radiance"])
print(circle:isValid())
print("Circle id "..circle:getUniqueIdentifier():toString())
print("Black body id "..black_body:getUniqueIdentifier():toString())
print("Alive entities: "..ox_alive_entities())